language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

before_install: set -e

script:
  - bash ci/script.sh

after_script: set +e

after_success:
  - bash ci/after_success.sh

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - master

notifications:
  email:
    on_success: never